config/routes.rb
Rails.application.routes.draw do
  resources :candidates
  resources :attributes
  resources :scorecards

  root 'scorecards#index'
  post '/compare' => 'candidates#compare'
end

app/models/attribute.rb
class Attribute < ActiveRecord::Base
  belongs_to :scorecard
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_one :scorecard

  def total_score number
    Candidate.find(number).score_01 + Candidate.find(number).score_02 +
    Candidate.find(number).score_03 + Candidate.find(number).score_04 +
    Candidate.find(number).score_05
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/scorecard.rb
class Scorecard < ActiveRecord::Base
  has_many :candidates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end
  
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @candidate = Candidate.all
  end

  def new
    @candidate = Candidate.new
    @scorecard = Scorecard.new(params[:id])
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      redirect_to candidates_path, alert: "New Candidate Saved!"
    else
      render :new
    end
  end

  def show
    @candidate = Candidate.new
  end

  def compare
    @candidate = Candidate.all
  end

  private

  def candidate_params
    params.require(:candidate).permit(:id, :scorecard_id, :interview_date, :name, :interviewer,
                                      :score_01, :score_02, :score_03, :score_04, :score_05)
  end
end

app/controllers/scorecards_controller.rb
class ScorecardsController < ApplicationController
  before_action :set_scorecard, only: [:show, :edit, :update, :destroy]

  def index
    @scorecard = Scorecard.all
  end

  def new
    @scorecard = Scorecard.new
  end

  def create
    @scorecard = Scorecard.new(scorecard_params)
    if @scorecard.save
      redirect_to scorecards_path, alert: "New Scorecard Saved!"
    else
      render :new
    end
  end

  def show
    @scorecard = Scorecard.new
  end

private

  def set_scorecard
    @scorecard = Scorecard.find_by(params[:name])
  end

  def scorecard_params
    params.require(:scorecard).permit(:id, :position, :industry, :attribute_name, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/scorecards_helper.rb
module ScorecardsHelper
end

app/views/candidates/compare.html.erb
<table>
  <thead>
    <tr>
      <th></th>
      <th><%= Candidate.find(1).name %></th>
      <th><%= Candidate.find(2).name %></th>
      <th><%= Candidate.find(3).name %></th>
      <th><%= Candidate.find(4).name %></th>
    </tr>
    <tr>
      <th>Relevant Experience</th>
      <td class="scores"><%= Candidate.find(1).score_01 %></td>
      <td class="scores"><%= Candidate.find(2).score_01 %></td>
      <td class="scores"><%= Candidate.find(3).score_01 %></td>
      <td class="scores"><%= Candidate.find(4).score_01 %></td>
    </tr>
    <tr>
      <th>Communication Skills</th>
      <td class="scores"><%= Candidate.find(1).score_02 %></td>
      <td class="scores"><%= Candidate.find(2).score_02 %></td>
      <td class="scores"><%= Candidate.find(3).score_02 %></td>
      <td class="scores"><%= Candidate.find(4).score_02 %></td>
    </tr>
    <tr>
      <th>Knowledge of Company</th>
      <td class="scores"><%= Candidate.find(1).score_03 %></td>
      <td class="scores"><%= Candidate.find(2).score_03 %></td>
      <td class="scores"><%= Candidate.find(3).score_03 %></td>
      <td class="scores"><%= Candidate.find(4).score_03 %></td>
    </tr>
    <tr>
      <th>Enthusiasm</th>
      <td class="scores"><%= Candidate.find(1).score_04 %></td>
      <td class="scores"><%= Candidate.find(2).score_04 %></td>
      <td class="scores"><%= Candidate.find(3).score_04 %></td>
      <td class="scores"><%= Candidate.find(4).score_04 %></td>
    </tr>
    <tr>
      <th>Cultural Fit</th>
      <td class="scores"><%= Candidate.find(1).score_05 %></td>
      <td class="scores"><%= Candidate.find(2).score_05 %></td>
      <td class="scores"><%= Candidate.find(3).score_05 %></td>
      <td class="scores"><%= Candidate.find(4).score_05 %></td>
    </tr>
    <tr>
      <th>Total</th>
      <td class="scores"><%= Candidate.find(1).total_score(1) %></td>
      <td class="scores"><%= Candidate.find(2).total_score(2) %></td>
      <td class="scores"><%= Candidate.find(3).total_score(3) %></td>
      <td class="scores"><%= Candidate.find(3).total_score(4) %></td>
    </tr>
  </thead>


</table>

app/views/candidates/index.html.erb
<h1>Candidates for this Scorecard</h1>

<table>
<% @candidate.order("LOWER(name)").each  do |cand| %>
  <tr>
    <td><%= cand.name %></td>
    <td><input id="accept" name="accept" type="checkbox" value=<%="#{cand.id}"%> /></td>
  </tr>  
<% end %>
</table>
<%= button_to "Compare Candidates", compare_path %>
<%= link_to "Back", scorecards_path, class:"btn btn-default" %>

app/views/candidates/new.html.erb
<%= form_for(@candidate) do |f| %>
  <table>
    <thead><h5> Scorecard Name </h5></thead>
    <tr>
      <td><em>Position</em></td>
      <td><%= f.date_select :interview_date %></td>
    </tr>
    <tr>
      <td><%= f.text_field :name, :placeholder => "Candidate Full Name" %></td>
      <td><%= f.text_field :interviewer, :placeholder => "Interviewer Name" %></td>
    </tr>
  </table><br><br>
  <table>
    <thead>Relevant Experience</thead>
    <tr>
      <td><%= f.radio_button(:score_01, "1") %><%= label_tag(:score_01, "1") %></td>
      <td><%= f.radio_button(:score_01, "2") %><%= label_tag(:score_01, "2") %></td>
      <td><%= f.radio_button(:score_01, "3") %><%= label_tag(:score_01, "3") %></td>
      <td><%= f.radio_button(:score_01, "4") %><%= label_tag(:score_01, "4") %></td>
      <td><%= f.radio_button(:score_01, "5") %><%= label_tag(:score_01, "5") %></td>
      <td><%= text_area_tag(:message, "Comments", size: "20x4") %></td>
    </tr>
  <table>
    <thead>Communication Skills</thead>
    <tr>
      <td><%= f.radio_button(:score_02, "1") %><%= label_tag(:score_02, "1") %></td>
      <td><%= f.radio_button(:score_02, "2") %><%= label_tag(:score_02, "2") %></td>
      <td><%= f.radio_button(:score_02, "3") %><%= label_tag(:score_02, "3") %></td>
      <td><%= f.radio_button(:score_02, "4") %><%= label_tag(:score_02, "4") %></td>
      <td><%= f.radio_button(:score_02, "5") %><%= label_tag(:score_02, "5") %></td>
      <td><%= text_area_tag(:message, "Comments", size: "20x4") %></td>
    </tr>
  <table>
    <thead>Knowledge of Company</thead>
    <tr>
      <td><%= f.radio_button(:score_03, "1") %><%= label_tag(:score_03, "1") %></td>
      <td><%= f.radio_button(:score_03, "2") %><%= label_tag(:score_03, "2") %></td>
      <td><%= f.radio_button(:score_03, "3") %><%= label_tag(:score_03, "3") %></td>
      <td><%= f.radio_button(:score_03, "4") %><%= label_tag(:score_03, "4") %></td>
      <td><%= f.radio_button(:score_03, "5") %><%= label_tag(:score_03, "5") %></td>
      <td><%= text_area_tag(:message, "Comments", size: "20x4") %></td>
    </tr>
  <table>
    <thead>Enthusiasm</thead>
    <tr>
      <td><%= f.radio_button(:score_04, "1") %><%= label_tag(:score_04, "1") %></td>
      <td><%= f.radio_button(:score_04, "2") %><%= label_tag(:score_04, "2") %></td>
      <td><%= f.radio_button(:score_04, "3") %><%= label_tag(:score_04, "3") %></td>
      <td><%= f.radio_button(:score_04, "4") %><%= label_tag(:score_04, "4") %></td>
      <td><%= f.radio_button(:score_04, "5") %><%= label_tag(:score_04, "5") %></td>
      <td><%= text_area_tag(:message, "Comments", size: "20x4") %></td>
    </tr>
  <table>
    <thead>Cultural Fit</thead>
    <tr>
      <td><%= f.radio_button(:score_05, "1") %><%= label_tag(:score_05, "1") %></td>
      <td><%= f.radio_button(:score_05, "2") %><%= label_tag(:score_05, "2") %></td>
      <td><%= f.radio_button(:score_05, "3") %><%= label_tag(:score_05, "3") %></td>
      <td><%= f.radio_button(:score_05, "4") %><%= label_tag(:score_05, "4") %></td>
      <td><%= f.radio_button(:score_05, "5") %><%= label_tag(:score_05, "5") %></td>
      <td><%= text_area_tag(:message, "Comments", size: "20x4") %></td>
    </tr><br>
  </table>
  <div class="actions">
    <%= f.submit %>
    <%= link_to "Edit this Scorecard", scorecards_path, class:"btn btn-default" %>
    <%= f.hidden_field :scorecard_id, :value => @scorecard.id %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/index.html.erb
<h1>Test</h1>

app/views/scorecards/_form.html.erb
<%= form_for(@scorecard) do |f| %>
<%= f.select :industry, ['Technology', 'Medicine', 'Hospitality', 'Sales']%><br>
<br>
<div class="field">
    <%= f.label :name, "Scorecard Name" %>
    <%= f.text_field :name %>
</div>
<div class="field">
    <%= f.label :position, "Position" %>
    <%= f.text_field :position %>
</div><br>
<%= f.label "Attributes" %>
<div class="field">
    <%= f.text_field :attribute_01, :value=> "Relevant Experience" %>
</div><br>
<div class="field">
    <%= f.text_field :attribute_02, :value=> "Communication Skills" %>
</div><br>
<div class="field">
    <%= f.text_field :attribute_03, :value=> "Knowledge of Company" %>
</div><br>
<div class="field">
    <%= f.text_field :attribute_04, :value=> "Enthusiasm" %>
</div><br>
<div class="field">
    <%= f.text_field :attribute_05, :value=> "Cultural Fit" %>
</div><br>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/scorecards/index.html.erb
<h1>Select a Scorecard</h1>

<%= link_to "Add a new scorecard", new_scorecard_path %>
<br><br>
<table>
  <thead>
    <tr>
      <th>Scorecard</th>
      <th>Position</th>
    </tr>
  </thead>
<% @scorecard.order("LOWER(name)").each  do |card| %>
  <tr>
    <td><%= link_to "#{card.name}", new_candidate_path %></td>
    <td><%= card.position %></td>
    <td><%= link_to "Show Candidates", candidates_path %></td>
  </tr>
 <% end %>
</table>

app/views/scorecards/new.html.erb
<h1>Scorecard creation</h1>

<%= render 'form' %>

app/views/scorecards/show.html.erb
<%= link_to "Edit this Scorecard", scorecard_path %>
<br>
<%= link_to "Create a new candidate using this Scorecard", new_candidate_path %>
<br><br>
<table>
  <thead>Scorecard Name</thead>
  <tr>
  <td>Position</td>
  <td>Date</td>
  </tr>

  <tr>
    <td>Name of Candidate</td>
    <td>Name of Interviewer</td>
  </tr>
</table>
<br>
<table>
  <thead>Relevant Experience</thead>
  <tr>
  <td><input type="checkbox" name="attribute1" value="1">1</td>
  <td><input type="checkbox" name="attribute1" value="2">2</td>
  <td><input type="checkbox" name="attribute1" value="3">3</td>
  <td><input type="checkbox" name="attribute1" value="4">4</td>
  <td><input type="checkbox" name="attribute1" value="5">5</td>
  <td><%= text_area_tag(:message, "Comments", size: "20x4") %></td>
  </tr>
</table>
<table>
  <thead>Communication Skills</thead>
  <td><input type="checkbox" name="attribute2" value="1">1</td>
  <td><input type="checkbox" name="attribute2" value="2">2</td>
  <td><input type="checkbox" name="attribute2" value="3">3</td>
  <td><input type="checkbox" name="attribute2" value="4">4</td>
  <td><input type="checkbox" name="attribute2" value="5">5</td>
  <td><%= text_area_tag(:message, "Comments", size: "20x4") %></td>
</table>
<table>
  <thead>Knowledge of Company</thead>
  <td><input type="checkbox" name="attribute3" value="1">1</td>
  <td><input type="checkbox" name="attribute3" value="2">2</td>
  <td><input type="checkbox" name="attribute3" value="3">3</td>
  <td><input type="checkbox" name="attribute3" value="4">4</td>
  <td><input type="checkbox" name="attribute3" value="5">5</td>
  <td><%= text_area_tag(:message, "Comments", size: "20x4") %></td>
  </table>
<table>
  <thead>Enthusiasm</thead>
  <td><input type="checkbox" name="attribute4" value="1">1</td>
  <td><input type="checkbox" name="attribute4" value="2">2</td>
  <td><input type="checkbox" name="attribute4" value="3">3</td>
  <td><input type="checkbox" name="attribute4" value="4">4</td>
  <td><input type="checkbox" name="attribute4" value="5">5</td>
  <td><%= text_area_tag(:message, "Comments", size: "20x4") %></td>
  </table>
<table>
  <thead>Cultural Fit</thead>
  <td><input type="checkbox" name="attribute5" value="1">1</td>
  <td><input type="checkbox" name="attribute5" value="2">2</td>
  <td><input type="checkbox" name="attribute5" value="3">3</td>
  <td><input type="checkbox" name="attribute5" value="4">4</td>
  <td><input type="checkbox" name="attribute5" value="5">5</td>
  <td><%= text_area_tag(:message, "Comments", size: "20x4") %></td>
</table>